// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package beer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CriticalPingClient is the client API for CriticalPing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CriticalPingClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type criticalPingClient struct {
	cc grpc.ClientConnInterface
}

func NewCriticalPingClient(cc grpc.ClientConnInterface) CriticalPingClient {
	return &criticalPingClient{cc}
}

func (c *criticalPingClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/beer.CriticalPing/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CriticalPingServer is the server API for CriticalPing service.
// All implementations must embed UnimplementedCriticalPingServer
// for forward compatibility
type CriticalPingServer interface {
	Ping(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedCriticalPingServer()
}

// UnimplementedCriticalPingServer must be embedded to have forward compatible implementations.
type UnimplementedCriticalPingServer struct {
}

func (UnimplementedCriticalPingServer) Ping(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCriticalPingServer) mustEmbedUnimplementedCriticalPingServer() {}

// UnsafeCriticalPingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CriticalPingServer will
// result in compilation errors.
type UnsafeCriticalPingServer interface {
	mustEmbedUnimplementedCriticalPingServer()
}

func RegisterCriticalPingServer(s grpc.ServiceRegistrar, srv CriticalPingServer) {
	s.RegisterService(&CriticalPing_ServiceDesc, srv)
}

func _CriticalPing_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CriticalPingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/beer.CriticalPing/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CriticalPingServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CriticalPing_ServiceDesc is the grpc.ServiceDesc for CriticalPing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CriticalPing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "beer.CriticalPing",
	HandlerType: (*CriticalPingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _CriticalPing_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
